"""empty message

Revision ID: 0d84ccb7b071
Revises: 9f7751b17601
Create Date: 2023-04-17 14:14:08.379493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0d84ccb7b071"
down_revision = "9f7751b17601"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "validation_payable_total",
            sa.Float(),
            server_default="0",
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "mapping_payable_total",
            sa.Float(),
            server_default="0",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "mapping_payable_total")
    op.drop_column("users", "validation_payable_total")
    # ### end Alembic commands ###
