"""empty message

Revision ID: 1db7523a7d84
Revises: 8d9725b98d3b
Create Date: 2024-01-12 09:13:11.137880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db7523a7d84'
down_revision = '8d9725b98d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_users', sa.Column('timestamp', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_users', 'timestamp')
    # ### end Alembic commands ###
