"""empty message

Revision ID: 3080a80378b9
Revises: 40bd5b768d50
Create Date: 2023-03-23 13:38:49.203676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3080a80378b9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("payoneer_id", sa.String(length=65), nullable=True),
        sa.Column("amount_paid", sa.Float(), nullable=True),
        sa.Column("user_name", sa.String(length=65), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("payment_email", sa.String(length=65), nullable=True),
        sa.Column("task_ids", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("date_paid", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("max_payment", sa.Float(), nullable=True),
        sa.Column("payment_due", sa.Float(), nullable=True),
        sa.Column("total_payout", sa.Float(), nullable=True),
        sa.Column("rate_per_task", sa.Float(), nullable=True),
        sa.Column("max_editors", sa.Integer(), nullable=False),
        sa.Column("total_editors", sa.BigInteger(), nullable=True),
        sa.Column("total_tasks", sa.BigInteger(), nullable=True),
        sa.Column("difficulty", sa.String(), nullable=True),
        sa.Column("tasks_mapped", sa.BigInteger(), nullable=True),
        sa.Column("tasks_validated", sa.BigInteger(), nullable=True),
        sa.Column("tasks_invalidated", sa.BigInteger(), nullable=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column(
            "visibility", sa.Boolean(), server_default="False", nullable=True
        ),
        sa.Column(
            "status", sa.Boolean(), server_default="False", nullable=True
        ),
        sa.Column(
            "completed", sa.Boolean(), server_default="False", nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_projects_deleted_date"),
        "projects",
        ["deleted_date"],
        unique=False,
    )
    op.create_table(
        "requests",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("amount_requested", sa.Float(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("user_name", sa.String(length=65), nullable=True),
        sa.Column("payment_email", sa.String(length=65), nullable=True),
        sa.Column("task_ids", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("date_requested", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=True),
        sa.Column("paid_out", sa.Boolean(), nullable=False),
        sa.Column("mapped", sa.Boolean(), nullable=True),
        sa.Column("validated", sa.Boolean(), nullable=True),
        sa.Column("invalidated", sa.Boolean(), nullable=True),
        sa.Column("mapped_by", sa.String(length=80), nullable=False),
        sa.Column("validated_by", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tasks_deleted_date"), "tasks", ["deleted_date"], unique=False
    )
    op.create_table(
        "training",
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("training_type", sa.String(), nullable=True),
        sa.Column("point_value", sa.Integer(), nullable=True),
        sa.Column("training_url", sa.String(), nullable=True),
        sa.Column("difficulty", sa.String(), nullable=True),
        sa.Column("question_1", sa.String(), nullable=True),
        sa.Column("answer_1", sa.String(), nullable=True),
        sa.Column("incorrect1_1", sa.String(), nullable=True),
        sa.Column("incorrect1_2", sa.String(), nullable=True),
        sa.Column("incorrect1_3", sa.String(), nullable=True),
        sa.Column("question_2", sa.String(), nullable=True),
        sa.Column("answer_2", sa.String(), nullable=True),
        sa.Column("incorrect2_1", sa.String(), nullable=True),
        sa.Column("incorrect2_2", sa.String(), nullable=True),
        sa.Column("incorrect2_3", sa.String(), nullable=True),
        sa.Column("question_3", sa.String(), nullable=True),
        sa.Column("answer_3", sa.String(), nullable=True),
        sa.Column("incorrect3_1", sa.String(), nullable=True),
        sa.Column("incorrect3_2", sa.String(), nullable=True),
        sa.Column("incorrect3_3", sa.String(), nullable=True),
        sa.Column("question_4", sa.String(), nullable=True),
        sa.Column("answer_4", sa.String(), nullable=True),
        sa.Column("incorrect4_1", sa.String(), nullable=True),
        sa.Column("incorrect4_2", sa.String(), nullable=True),
        sa.Column("incorrect4_3", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_deleted_date"),
        "training",
        ["deleted_date"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("payment_email", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("osm_username", sa.String(), nullable=True),
        sa.Column("org_id", sa.BigInteger(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("create_time", sa.DateTime(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column(
            "assigned_projects", postgresql.ARRAY(sa.Integer()), nullable=True
        ),
        sa.Column("mapper_level", sa.Integer(), nullable=True),
        sa.Column(
            "payable_total", sa.Float(), server_default="0", nullable=True
        ),
        sa.Column(
            "requested_total", sa.Float(), server_default="0", nullable=True
        ),
        sa.Column("paid_total", sa.Float(), server_default="0", nullable=True),
        sa.Column(
            "total_tasks_mapped",
            sa.BigInteger(),
            server_default="0",
            nullable=True,
        ),
        sa.Column(
            "total_tasks_validated",
            sa.BigInteger(),
            server_default="0",
            nullable=True,
        ),
        sa.Column(
            "total_tasks_invalidated",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "requesting_payment",
            sa.Boolean(),
            server_default="False",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("osm_username"),
        sa.UniqueConstraint("payment_email"),
    )
    op.create_index(
        op.f("ix_users_deleted_date"), "users", ["deleted_date"], unique=False
    )
    op.create_table(
        "project_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "training_completed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("training_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["training_id"], ["training.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_tasks")
    op.drop_table("training_completed")
    op.drop_table("project_users")
    op.drop_index(op.f("ix_users_deleted_date"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_training_deleted_date"), table_name="training")
    op.drop_table("training")
    op.drop_index(op.f("ix_tasks_deleted_date"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("requests")
    op.drop_index(op.f("ix_projects_deleted_date"), table_name="projects")
    op.drop_table("projects")
    op.drop_table("payments")
    # ### end Alembic commands ###
