"""empty message

Revision ID: 30af068da711
Revises: 2f3b80dc99e1
Create Date: 2023-05-22 14:43:49.261512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "30af068da711"
down_revision = "2f3b80dc99e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("task_id", sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "task_id")
    # ### end Alembic commands ###
