"""empty message

Revision ID: 4e2ac6505d90
Revises: 4f43c721b681
Create Date: 2023-05-02 17:59:26.319078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e2ac6505d90"
down_revision = "4f43c721b681"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_checklists", sa.Column("user_id", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "user_checklists",
        sa.Column("checklist_id", sa.BigInteger(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_checklists", "checklist_id")
    op.drop_column("user_checklists", "user_id")
    # ### end Alembic commands ###
