"""empty message

Revision ID: 8adadbe61369
Revises: 50a152b781cf
Create Date: 2023-05-02 17:53:53.053801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8adadbe61369"
down_revision = "50a152b781cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_checklist_item",
        sa.Column("user_id", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "user_checklist_item",
        sa.Column("checklist_id", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "user_checklists", sa.Column("user_id", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "user_checklists",
        sa.Column("checklist_id", sa.BigInteger(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_checklists", "checklist_id")
    op.drop_column("user_checklists", "user_id")
    op.drop_column("user_checklist_item", "checklist_id")
    op.drop_column("user_checklist_item", "user_id")
    # ### end Alembic commands ###
