"""empty message

Revision ID: be1b4f86edf2
Revises: 4e2ac6505d90
Create Date: 2023-05-03 13:47:09.828021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "be1b4f86edf2"
down_revision = "4e2ac6505d90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "checklist_payable_total",
            sa.Float(),
            server_default="0",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "checklist_payable_total")
    # ### end Alembic commands ###
