"""empty message

Revision ID: cc82c687300d
Revises: 4fcd807d6ab3
Create Date: 2023-12-18 10:52:59.976154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cc82c687300d"
down_revision = "4fcd807d6ab3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "user_tasks",
        sa.Column(
            "timestamp",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("(now() at time zone 'utc')"),
        ),
    )


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_tasks", "timestamp")
    # ### end Alembic commands ###
