"""empty message

Revision ID: fd67ddb3ffe2
Revises: 6e8f3f1abe5a
Create Date: 2023-05-02 10:43:19.378953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fd67ddb3ffe2"
down_revision = "6e8f3f1abe5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "checklists",
        sa.Column(
            "active_status",
            sa.Boolean(),
            server_default="False",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("checklists", "active_status")
    # ### end Alembic commands ###
