"""empty message

Revision ID: 08f61e466739
Revises: 5270f02f9747
Create Date: 2023-03-22 16:54:56.625761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "08f61e466739"
down_revision = "5270f02f9747"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("training_completed")
    op.drop_index("ix_training_deleted_date", table_name="training")
    op.drop_table("training")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "deleted_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("org_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "training_type", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "point_value", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "training_url", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "difficulty", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "question_1", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "answer_1", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "incorrect1_1", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "incorrect1_2", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "incorrect1_3", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "question_2", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "answer_2", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "incorrect2_1", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "incorrect2_2", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "incorrect2_3", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "question_3", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "answer_3", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "incorrect3_1", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "incorrect3_2", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "incorrect3_3", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "question_4", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "answer_4", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "incorrect4_1", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "incorrect4_2", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "incorrect4_3", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="training_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "ix_training_deleted_date", "training", ["deleted_date"], unique=False
    )
    op.create_table(
        "training_completed",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "training_id", sa.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["training_id"],
            ["training.id"],
            name="training_completed_training_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="training_completed_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="training_completed_pkey"),
    )
    # ### end Alembic commands ###
