"""empty message

Revision ID: 09098b77760b
Revises: f6ee93084670
Create Date: 2023-04-17 12:15:17.861356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "09098b77760b"
down_revision = "f6ee93084670"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "validator_tasks_invalidated",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "users",
        "validator_tasks_validated",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "validator_tasks_validated",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "users",
        "validator_tasks_invalidated",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###
