"""empty message

Revision ID: 0a8c98d10db5
Revises: a05b002858b8
Create Date: 2023-05-01 10:22:15.254018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a8c98d10db5"
down_revision = "a05b002858b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checklists",
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("max_payment", sa.Float(), nullable=True),
        sa.Column("payment_due", sa.Float(), nullable=True),
        sa.Column("total_payout", sa.Float(), nullable=True),
        sa.Column("validation_rate", sa.Float(), nullable=True),
        sa.Column("completion_rate", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column(
            "visibility", sa.Boolean(), server_default="False", nullable=True
        ),
        sa.Column(
            "status", sa.Boolean(), server_default="False", nullable=True
        ),
        sa.Column(
            "completed", sa.Boolean(), server_default="False", nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_checklists_deleted_date"),
        "checklists",
        ["deleted_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_checklists_deleted_date"), table_name="checklists")
    op.drop_table("checklists")
    # ### end Alembic commands ###
