"""empty message

Revision ID: 0cb003b31ceb
Revises: 44718089c68c
Create Date: 2023-05-08 13:02:19.565671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0cb003b31ceb"
down_revision = "44718089c68c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "assigned_checklists",
            postgresql.ARRAY(sa.Integer()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "assigned_checklists")
    # ### end Alembic commands ###
