"""empty message

Revision ID: 10179d3aa13e
Revises: 5ecfce745853
Create Date: 2023-05-01 14:29:29.064620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10179d3aa13e'
down_revision = '5ecfce745853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('checklist_item_checklist_id_fkey', 'checklist_item', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('checklist_item_checklist_id_fkey', 'checklist_item', 'checklists', ['checklist_id'], ['id'])
    # ### end Alembic commands ###
