"""empty message

Revision ID: 11f8d916aae1
Revises: e19005a5a156
Create Date: 2023-02-20 19:35:58.345022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "11f8d916aae1"
down_revision = "e19005a5a156"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "awaiting_payment", sa.Float(), server_default="0", nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "accured_payment", sa.Float(), server_default="0", nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "total_tasks_mapped",
            sa.BigInteger(),
            server_default="0",
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "total_tasks_validated",
            sa.BigInteger(),
            server_default="0",
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "total_tasks_invalidated",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "requesting_payment",
            sa.Boolean(),
            server_default="False",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "requesting_payment")
    op.drop_column("users", "total_tasks_invalidated")
    op.drop_column("users", "total_tasks_validated")
    op.drop_column("users", "total_tasks_mapped")
    op.drop_column("users", "accured_payment")
    op.drop_column("users", "awaiting_payment")
    # ### end Alembic commands ###
