"""empty message

Revision ID: 16f08eab99bc
Revises: 84a12353ba4c
Create Date: 2023-02-22 21:30:16.474825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f08eab99bc'
down_revision = '84a12353ba4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'name')
    # ### end Alembic commands ###
