"""empty message

Revision ID: 186dab04e5bb
Revises: 855e2e3a1172
Create Date: 2023-03-02 11:53:57.620090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "186dab04e5bb"
down_revision = "855e2e3a1172"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "status", sa.Boolean(), server_default="False", nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "status")
    # ### end Alembic commands ###
