"""empty message

Revision ID: 19c3d19399c2
Revises: 41211ef4132e
Create Date: 2023-02-28 11:23:36.754515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "19c3d19399c2"
down_revision = "41211ef4132e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("org_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "org_id")
    # ### end Alembic commands ###
