"""empty message

Revision ID: 1a7aed71a6fe
Revises: c3c3a0684a81
Create Date: 2023-03-23 13:46:54.752919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1a7aed71a6fe"
down_revision = "c3c3a0684a81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("training", "incorrect")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training",
        sa.Column(
            "incorrect", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
