"""empty message

Revision ID: 211d48c64001
Revises: 4003d44495a7
Create Date: 2023-05-01 17:41:02.363870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '211d48c64001'
down_revision = '4003d44495a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_checklist_item_deleted_date', table_name='checklist_item')
    op.drop_table('checklist_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_item',
    sa.Column('deleted_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('checklist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('item_action', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('item_link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('item_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='checklist_item_pkey')
    )
    op.create_index('ix_checklist_item_deleted_date', 'checklist_item', ['deleted_date'], unique=False)
    # ### end Alembic commands ###
