"""empty message

Revision ID: 243f1091126b
Revises: 5421a0509983
Create Date: 2023-05-01 14:31:40.354323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243f1091126b'
down_revision = '5421a0509983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklists',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_comment', sa.String(), nullable=True),
    sa.Column('validator_comment', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('max_payment', sa.Float(), nullable=True),
    sa.Column('payment_due', sa.Float(), nullable=True),
    sa.Column('total_payout', sa.Float(), nullable=True),
    sa.Column('validation_rate', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('visibility', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('status', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('completed', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('confirmed', sa.Boolean(), server_default='False', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklists_deleted_date'), 'checklists', ['deleted_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklists_deleted_date'), table_name='checklists')
    op.drop_table('checklists')
    # ### end Alembic commands ###
