"""empty message

Revision ID: 24f0829ff634
Revises: 6a74ffe06b83
Create Date: 2023-03-15 14:10:54.059184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f0829ff634'
down_revision = '6a74ffe06b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('point_value', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('question_1', sa.String(), nullable=True),
    sa.Column('answer_1', sa.String(), nullable=True),
    sa.Column('question_2', sa.String(), nullable=True),
    sa.Column('answer_2', sa.String(), nullable=True),
    sa.Column('question_3', sa.String(), nullable=True),
    sa.Column('answer_3', sa.String(), nullable=True),
    sa.Column('question_4', sa.String(), nullable=True),
    sa.Column('answer_4', sa.String(), nullable=True),
    sa.Column('question_5', sa.String(), nullable=True),
    sa.Column('answer_5', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_deleted_date'), 'training', ['deleted_date'], unique=False)
    op.add_column('project_users', sa.Column('training_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'project_users', 'training', ['training_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_users', type_='foreignkey')
    op.drop_column('project_users', 'training_id')
    op.drop_index(op.f('ix_training_deleted_date'), table_name='training')
    op.drop_table('training')
    # ### end Alembic commands ###
