"""add changeset_adiffs table

Revision ID: 2966333a6cfa
Revises: 8cffcdbdaa37
Create Date: 2026-05-19 15:32:42.448543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2966333a6cfa'
down_revision = '8cffcdbdaa37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changeset_adiffs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=255), nullable=False),
    sa.Column('changeset_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('osm_user', sa.String(length=255), nullable=True),
    sa.Column('adiff_xml', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'changeset_id', name='uq_changeset_adiff_org')
    )
    with op.batch_alter_table('changeset_adiffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_changeset_adiffs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_changeset_adiffs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_changeset_adiffs_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_changeset_adiffs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('element_analysis_cache', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_element_analysis_cache_org_day_cat'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('element_analysis_cache', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_element_analysis_cache_org_day_cat'), ['org_id', 'day', 'category'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('changeset_adiffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_changeset_adiffs_user_id'))
        batch_op.drop_index(batch_op.f('ix_changeset_adiffs_team_id'))
        batch_op.drop_index(batch_op.f('ix_changeset_adiffs_org_id'))
        batch_op.drop_index(batch_op.f('ix_changeset_adiffs_created_at'))

    op.drop_table('changeset_adiffs')
    # ### end Alembic commands ###
