"""empty message

Revision ID: 2c463fa5872b
Revises: d2f630510f21
Create Date: 2023-02-28 22:09:18.544104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c463fa5872b"
down_revision = "d2f630510f21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("amount_paid", sa.Integer(), nullable=True)
    )
    op.add_column(
        "requests", sa.Column("amount_requested", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requests", "amount_requested")
    op.drop_column("payments", "amount_paid")
    # ### end Alembic commands ###
