"""empty message

Revision ID: 2d3b926f1148
Revises: 0a8c98d10db5
Create Date: 2023-05-01 10:51:36.673280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3b926f1148'
down_revision = '0a8c98d10db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_item',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('item_task', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_item_deleted_date'), 'checklist_item', ['deleted_date'], unique=False)
    op.add_column('checklists', sa.Column('author', sa.String(), nullable=True))
    op.add_column('checklists', sa.Column('description', sa.String(), nullable=True))
    op.add_column('checklists', sa.Column('user_comment', sa.String(), nullable=True))
    op.add_column('checklists', sa.Column('validator_comment', sa.String(), nullable=True))
    op.add_column('checklists', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('checklists', sa.Column('confirmed', sa.Boolean(), server_default='False', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklists', 'confirmed')
    op.drop_column('checklists', 'due_date')
    op.drop_column('checklists', 'validator_comment')
    op.drop_column('checklists', 'user_comment')
    op.drop_column('checklists', 'description')
    op.drop_column('checklists', 'author')
    op.drop_index(op.f('ix_checklist_item_deleted_date'), table_name='checklist_item')
    op.drop_table('checklist_item')
    # ### end Alembic commands ###
