"""empty message

Revision ID: 2f3b80dc99e1
Revises: a0cd0889b028
Create Date: 2023-05-10 12:10:25.272352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f3b80dc99e1"
down_revision = "a0cd0889b028"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("unknown_validator", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "unknown_validator")
    # ### end Alembic commands ###
