"""empty message

Revision ID: 3bb688c855fe
Revises: 16f08eab99bc
Create Date: 2023-02-22 22:00:09.277785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3bb688c855fe"
down_revision = "16f08eab99bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("difficulty", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "difficulty")
    # ### end Alembic commands ###
