"""empty message

Revision ID: 3d931b5b2ae2
Revises: eadc6f28b106
Create Date: 2023-02-28 14:57:44.083819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d931b5b2ae2"
down_revision = "eadc6f28b106"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests", sa.Column("amount_paid", sa.Integer(), nullable=True)
    )
    op.add_column(
        "requests", sa.Column("user_paid", sa.String(length=65), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requests", "user_paid")
    op.drop_column("requests", "amount_paid")
    # ### end Alembic commands ###
