"""empty message

Revision ID: 3df7dc6066e1
Revises: 25e954584ccc
Create Date: 2023-03-03 22:55:26.304151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3df7dc6066e1"
down_revision = "25e954584ccc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "payable_total", sa.Float(), server_default="0", nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "requested_total", sa.Float(), server_default="0", nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column("paid_total", sa.Float(), server_default="0", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "paid_total")
    op.drop_column("users", "requested_total")
    op.drop_column("users", "payable_total")
    # ### end Alembic commands ###
