"""empty message

Revision ID: 4003d44495a7
Revises: 243f1091126b
Create Date: 2023-05-01 15:39:07.502045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4003d44495a7"
down_revision = "243f1091126b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "checklist_item", sa.Column("item_number", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("checklist_item", "item_number")
    # ### end Alembic commands ###
