"""empty message

Revision ID: 41211ef4132e
Revises: 71cd6b012739
Create Date: 2023-02-28 11:03:34.897352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41211ef4132e'
down_revision = '71cd6b012739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'paid')
    # ### end Alembic commands ###
