"""empty message

Revision ID: 44718089c68c
Revises: be1b4f86edf2
Create Date: 2023-05-03 13:48:44.529091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44718089c68c"
down_revision = "be1b4f86edf2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "total_checklists_completed",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "validator_total_checklists_confirmed",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "validator_total_checklists_confirmed")
    op.drop_column("users", "total_checklists_completed")
    # ### end Alembic commands ###
