"""empty message

Revision ID: 45c1bc00dcd8
Revises: c869ebb40b0e
Create Date: 2023-02-28 10:08:41.517470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c1bc00dcd8'
down_revision = 'c869ebb40b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('paid_out', sa.Boolean(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('mapped_by', sa.String(length=80), nullable=False),
    sa.Column('validated_by', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_deleted_date'), 'tasks', ['deleted_date'], unique=False)
    op.add_column('projects', sa.Column('active', sa.Boolean(), server_default='False', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'active')
    op.drop_index(op.f('ix_tasks_deleted_date'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
