"""empty message

Revision ID: 465c43c7f7da
Revises: 9e38ca0e2751
Create Date: 2023-03-22 15:53:24.186142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "465c43c7f7da"
down_revision = "9e38ca0e2751"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training", sa.Column("deleted_date", sa.DateTime(), nullable=True)
    )
    op.create_index(
        op.f("ix_training_deleted_date"),
        "training",
        ["deleted_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_training_deleted_date"), table_name="training")
    op.drop_column("training", "deleted_date")
    # ### end Alembic commands ###
