"""empty message

Revision ID: 46ef198f16bc
Revises: 677a121862ca
Create Date: 2023-02-28 17:46:09.393338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "46ef198f16bc"
down_revision = "677a121862ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("payoneer_id", sa.String(length=65), nullable=True),
        sa.Column("amount_paid", sa.Integer(), nullable=True),
        sa.Column("user_paid", sa.String(length=65), nullable=True),
        sa.Column("payment_email", sa.String(length=65), nullable=True),
        sa.Column("task_ids", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("date_paid", sa.String(length=65), nullable=True),
        sa.Column("notes", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("requests", "date_paid")
    op.drop_column("requests", "amount_paid")
    op.drop_column("requests", "user_paid")
    op.drop_column("requests", "payoneer_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests",
        sa.Column(
            "payoneer_id",
            sa.VARCHAR(length=65),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "requests",
        sa.Column(
            "user_paid",
            sa.VARCHAR(length=65),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "requests",
        sa.Column(
            "amount_paid", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "requests",
        sa.Column(
            "date_paid",
            sa.VARCHAR(length=65),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_table("payments")
    # ### end Alembic commands ###
