"""empty message

Revision ID: 49349df8f7f2
Revises: 1a7aed71a6fe
Create Date: 2023-03-23 22:04:47.115137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "49349df8f7f2"
down_revision = "1a7aed71a6fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("mapper_points", sa.Integer(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("validator_points", sa.Integer(), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("special_project_points", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "special_project_points")
    op.drop_column("users", "validator_points")
    op.drop_column("users", "mapper_points")
    # ### end Alembic commands ###
