"""empty message

Revision ID: 4f43c721b681
Revises: 8adadbe61369
Create Date: 2023-05-02 17:58:20.776435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f43c721b681'
down_revision = '8adadbe61369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_checklists', sa.Column('name', sa.String(), nullable=True))
    op.add_column('user_checklists', sa.Column('author', sa.String(), nullable=True))
    op.add_column('user_checklists', sa.Column('description', sa.String(), nullable=True))
    op.add_column('user_checklists', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('user_checklists', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('user_checklists', sa.Column('total_payout', sa.Float(), nullable=True))
    op.add_column('user_checklists', sa.Column('validation_rate', sa.Float(), nullable=True))
    op.add_column('user_checklists', sa.Column('completion_rate', sa.Float(), nullable=True))
    op.add_column('user_checklists', sa.Column('difficulty', sa.String(), nullable=True))
    op.add_column('user_checklists', sa.Column('visibility', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('user_checklists', sa.Column('active_status', sa.Boolean(), server_default='False', nullable=True))
    op.drop_column('user_checklists', 'payment_due')
    op.drop_column('user_checklists', 'user_id')
    op.drop_column('user_checklists', 'checklist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_checklists', sa.Column('checklist_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('user_checklists', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('user_checklists', sa.Column('payment_due', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('user_checklists', 'active_status')
    op.drop_column('user_checklists', 'visibility')
    op.drop_column('user_checklists', 'difficulty')
    op.drop_column('user_checklists', 'completion_rate')
    op.drop_column('user_checklists', 'validation_rate')
    op.drop_column('user_checklists', 'total_payout')
    op.drop_column('user_checklists', 'org_id')
    op.drop_column('user_checklists', 'due_date')
    op.drop_column('user_checklists', 'description')
    op.drop_column('user_checklists', 'author')
    op.drop_column('user_checklists', 'name')
    # ### end Alembic commands ###
