"""empty message

Revision ID: 4fcd807d6ab3
Revises: 0de5b51ab950
Create Date: 2023-12-18 09:53:26.208967

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = "4fcd807d6ab3"
down_revision = "0de5b51ab950"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column with nullable=True
    op.add_column(
        "projects",
        sa.Column(
            "timestamp",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("(now() at time zone 'utc')"),
        ),
    )

    # Set default values for existing rows
    # default_timestamp = datetime.utcnow()
    # op.execute(
    #     "UPDATE projects SET timestamp = :default_timestamp WHERE timestamp IS NULL",
    #     {"default_timestamp": default_timestamp},  # Correct parameter naming
    # )

    # # Modify the column to be non-nullable
    # op.alter_column("projects", "timestamp", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "timestamp")
    # ### end Alembic commands ###
