"""empty message

Revision ID: 50a152b781cf
Revises: b8d38a741f0f
Create Date: 2023-05-02 17:46:53.253637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "50a152b781cf"
down_revision = "b8d38a741f0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_checklist_item", "checklist_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_checklist_item",
        sa.Column(
            "checklist_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
