"""empty message

Revision ID: 5313030d1e8a
Revises: 11f8d916aae1
Create Date: 2023-02-20 19:44:56.478662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5313030d1e8a"
down_revision = "11f8d916aae1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "assigned_projects", postgresql.ARRAY(sa.Integer()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "assigned_projects")
    # ### end Alembic commands ###
