"""empty message

Revision ID: 577e0a60ee7a
Revises: ea39a0d14d10
Create Date: 2023-02-28 10:30:09.655877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "577e0a60ee7a"
down_revision = "ea39a0d14d10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payRequests",
        sa.Column("id", sa.BigInteger(), nullable=True),
        sa.Column("payoneer_id", sa.String(length=65), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("user_requesting", sa.String(length=65), nullable=True),
        sa.Column("payment_email", sa.String(length=65), nullable=True),
        sa.Column("task_ids", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("date_paid", sa.String(length=65), nullable=True),
        sa.Column("date_requested", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payRequests")
    # ### end Alembic commands ###
