"""empty message

Revision ID: 58c8320ff6c3
Revises: 989d98a4c9f7
Create Date: 2023-03-22 13:50:32.813843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58c8320ff6c3"
down_revision = "989d98a4c9f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("training", "false_2_question_1")
    op.drop_column("training", "question_3")
    op.drop_column("training", "false_1_question_1")
    op.drop_column("training", "false_3_question_2")
    op.drop_column("training", "answer_question_4")
    op.drop_column("training", "answer_question_2")
    op.drop_column("training", "false_3_question_4")
    op.drop_column("training", "question_1")
    op.drop_column("training", "answer_question_3")
    op.drop_column("training", "false_2_question_4")
    op.drop_column("training", "question_4")
    op.drop_column("training", "false_1_question_4")
    op.drop_column("training", "false_3_question_1")
    op.drop_column("training", "false_2_question_2")
    op.drop_column("training", "question_2")
    op.drop_column("training", "answer_question_1")
    op.drop_column("training", "false_1_question_3")
    op.drop_column("training", "false_2_question_3")
    op.drop_column("training", "false_3_question_3")
    op.drop_column("training", "false_1_question_2")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training",
        sa.Column(
            "false_1_question_2",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "false_3_question_3",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "false_2_question_3",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "false_1_question_3",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "answer_question_1",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "question_2", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "false_2_question_2",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "false_3_question_1",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "false_1_question_4",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "question_4", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "false_2_question_4",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "answer_question_3",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "question_1", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "false_3_question_4",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "answer_question_2",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "answer_question_4",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "false_3_question_2",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "false_1_question_1",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "question_3", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "false_2_question_1",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
