"""empty message

Revision ID: 5acb98a02813
Revises: d1868ed81960
Create Date: 2023-03-01 14:14:44.385604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5acb98a02813"
down_revision = "d1868ed81960"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("date_paid", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "date_paid")
    # ### end Alembic commands ###
