"""empty message

Revision ID: 5c3595555757
Revises: b91babfb101c
Create Date: 2023-03-22 17:32:26.647070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c3595555757"
down_revision = "b91babfb101c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("training", sa.Column("title", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("training", "title")
    # ### end Alembic commands ###
