"""empty message

Revision ID: 5d5c09b5c53a
Revises: 5acb98a02813
Create Date: 2023-03-01 17:11:22.147676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5c09b5c53a'
down_revision = '5acb98a02813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'amount_paid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('amount_paid', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
