"""empty message

Revision ID: 5ecfce745853
Revises: 2d3b926f1148
Create Date: 2023-05-01 14:20:20.602304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5ecfce745853"
down_revision = "2d3b926f1148"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "checklist_item", sa.Column("item_action", sa.String(), nullable=True)
    )
    op.add_column(
        "checklist_item", sa.Column("item_link", sa.String(), nullable=True)
    )
    op.drop_column("checklist_item", "item_task")
    op.drop_column("checklists", "url")
    op.drop_column("checklists", "source")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "checklists",
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "checklists",
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "checklist_item",
        sa.Column(
            "item_task", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("checklist_item", "item_link")
    op.drop_column("checklist_item", "item_action")
    # ### end Alembic commands ###
