"""empty message

Revision ID: 5f907259b146
Revises: 30af068da711
Create Date: 2023-05-22 14:54:20.081420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5f907259b146"
down_revision = "30af068da711"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("task_id", sa.BigInteger(), nullable=True)
    )
    op.drop_column("users", "task_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("task_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.drop_column("tasks", "task_id")
    # ### end Alembic commands ###
