"""empty message

Revision ID: 619e7880f9d7
Revises: 75821dd84608
Create Date: 2023-03-01 11:41:18.167868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "619e7880f9d7"
down_revision = "75821dd84608"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("user_name", sa.String(length=65), nullable=True)
    )
    op.add_column(
        "payments", sa.Column("user_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "user_id")
    op.drop_column("payments", "user_name")
    # ### end Alembic commands ###
