"""empty message

Revision ID: 64f00bafec75
Revises: 45c1bc00dcd8
Create Date: 2023-02-28 10:16:33.108119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f00bafec75'
down_revision = '45c1bc00dcd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('completed', sa.Boolean(), server_default='False', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'completed')
    # ### end Alembic commands ###
