"""empty message

Revision ID: 677a121862ca
Revises: 3d931b5b2ae2
Create Date: 2023-02-28 17:44:32.375403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677a121862ca'
down_revision = '3d931b5b2ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'paid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
