"""empty message

Revision ID: 6a74ffe06b83
Revises: f5f1770a0697
Create Date: 2023-03-15 14:09:46.100694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a74ffe06b83'
down_revision = 'f5f1770a0697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_users', 'project_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.add_column('users', sa.Column('mapper_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mapper_level')
    op.alter_column('project_users', 'project_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('project_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
