"""empty message

Revision ID: 6e8f3f1abe5a
Revises: 211d48c64001
Create Date: 2023-05-01 17:41:24.613303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8f3f1abe5a'
down_revision = '211d48c64001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_item',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('item_number', sa.Integer(), nullable=True),
    sa.Column('item_action', sa.String(), nullable=True),
    sa.Column('item_link', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_item_deleted_date'), 'checklist_item', ['deleted_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklist_item_deleted_date'), table_name='checklist_item')
    op.drop_table('checklist_item')
    # ### end Alembic commands ###
