"""empty message

Revision ID: 6f1f8c3ab191
Revises: d018e4ae2137
Create Date: 2023-02-28 10:40:06.129412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6f1f8c3ab191"
down_revision = "d018e4ae2137"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payRequests",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("payoneer_id", sa.String(length=65), nullable=True),
        sa.Column("amount_requested", sa.Integer(), nullable=True),
        sa.Column("user_requesting", sa.String(length=65), nullable=True),
        sa.Column("payment_email", sa.String(length=65), nullable=True),
        sa.Column("task_ids", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("date_paid", sa.String(length=65), nullable=True),
        sa.Column("date_requested", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_users")
    op.drop_table("payRequests")
    # ### end Alembic commands ###
