"""empty message

Revision ID: 6fef7f44b5bb
Revises: c333dc50873e
Create Date: 2023-03-22 14:03:13.436522

"""

# revision identifiers, used by Alembic.
revision = "6fef7f44b5bb"
down_revision = "c333dc50873e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
