"""empty message

Revision ID: 71cd6b012739
Revises: bb56365d6a24
Create Date: 2023-02-28 10:42:30.756139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "71cd6b012739"
down_revision = "bb56365d6a24"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requests",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("payoneer_id", sa.String(length=65), nullable=True),
        sa.Column("amount_requested", sa.Integer(), nullable=True),
        sa.Column("user_requesting", sa.String(length=65), nullable=True),
        sa.Column("payment_email", sa.String(length=65), nullable=True),
        sa.Column("task_ids", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("date_paid", sa.String(length=65), nullable=True),
        sa.Column("date_requested", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("requests")
    # ### end Alembic commands ###
