"""empty message

Revision ID: 7307d0b8860d
Revises: 80069eac8fe4
Create Date: 2023-03-15 14:12:01.660274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7307d0b8860d"
down_revision = "80069eac8fe4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_completed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("training_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["training_id"], ["training.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("training_completed")
    # ### end Alembic commands ###
