"""empty message

Revision ID: 75821dd84608
Revises: 2c463fa5872b
Create Date: 2023-03-01 11:41:10.754620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75821dd84608'
down_revision = '2c463fa5872b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'user_paid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('user_paid', sa.VARCHAR(length=65), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
