"""empty message

Revision ID: 80069eac8fe4
Revises: 24f0829ff634
Create Date: 2023-03-15 14:11:53.798735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "80069eac8fe4"
down_revision = "24f0829ff634"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "project_users_training_id_fkey", "project_users", type_="foreignkey"
    )
    op.drop_column("project_users", "training_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_users",
        sa.Column(
            "training_id", sa.BIGINT(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "project_users_training_id_fkey",
        "project_users",
        "training",
        ["training_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
