"""empty message

Revision ID: 80f35b1129df
Revises: cb6f4a48a267
Create Date: 2023-02-20 17:58:57.595013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "80f35b1129df"
down_revision = "cb6f4a48a267"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("payment_email", sa.String(), nullable=True)
    )
    op.add_column("users", sa.Column("city", sa.String(), nullable=True))
    op.add_column("users", sa.Column("country", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("osm_username", sa.String(), nullable=True)
    )
    op.create_unique_constraint(None, "users", ["city"])
    op.create_unique_constraint(None, "users", ["country"])
    op.create_unique_constraint(None, "users", ["osm_username"])
    op.create_unique_constraint(None, "users", ["payment_email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "osm_username")
    op.drop_column("users", "country")
    op.drop_column("users", "city")
    op.drop_column("users", "payment_email")
    # ### end Alembic commands ###
