"""empty message

Revision ID: 84a12353ba4c
Revises: d12095b6dada
Create Date: 2023-02-22 21:10:37.467081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a12353ba4c'
down_revision = 'd12095b6dada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('org_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'org_id')
    # ### end Alembic commands ###
