"""empty message

Revision ID: 85262c64e8d6
Revises: 5313030d1e8a
Create Date: 2023-02-21 21:52:29.767732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "85262c64e8d6"
down_revision = "5313030d1e8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("max_payment", sa.Integer(), nullable=False),
        sa.Column("payment_due", sa.Integer(), nullable=False),
        sa.Column("total_payout", sa.Integer(), nullable=False),
        sa.Column("rate_per_task", sa.Integer(), nullable=False),
        sa.Column("max_editors", sa.Integer(), nullable=False),
        sa.Column("total_editors", sa.BigInteger(), nullable=True),
        sa.Column("total_tasks", sa.BigInteger(), nullable=True),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_projects_deleted_date"),
        "projects",
        ["deleted_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_deleted_date"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
