"""empty message

Revision ID: 852886268a9f
Revises: 586c28ef0047
Create Date: 2024-05-23 10:32:16.832421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852886268a9f'
down_revision = '586c28ef0047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_users', sa.Column('timestamp', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_users', 'timestamp')
    # ### end Alembic commands ###
