"""empty message

Revision ID: 855e2e3a1172
Revises: ab8ccbb56b04
Create Date: 2023-03-02 11:53:33.612639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855e2e3a1172'
down_revision = 'ab8ccbb56b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
