"""empty message

Revision ID: 867eae940d7e
Revises: 619e7880f9d7
Create Date: 2023-03-01 11:52:15.718814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867eae940d7e'
down_revision = '619e7880f9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'user_requesting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('user_requesting', sa.VARCHAR(length=65), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
