"""empty message

Revision ID: 8d9725b98d3b
Revises: 31705d2ba4ac
Create Date: 2024-01-04 10:15:03.547673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = "8d9725b98d3b"
down_revision = "31705d2ba4ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_tasks",
        sa.Column(
            "timestamp", sa.TIMESTAMP(), server_default=text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_tasks", "timestamp")
    # ### end Alembic commands ###
