"""empty message

Revision ID: 8ea51a48b97b
Revises: b4683f439b92
Create Date: 2023-03-22 15:03:58.494648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ea51a48b97b"
down_revision = "b4683f439b92"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training", sa.Column("question_2", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("answer_2", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect2_1", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect2_2", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect2_3", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("question_3", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("answer_3", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect3_1", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect3_2", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect3_3", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("training", "incorrect3_3")
    op.drop_column("training", "incorrect3_2")
    op.drop_column("training", "incorrect3_1")
    op.drop_column("training", "answer_3")
    op.drop_column("training", "question_3")
    op.drop_column("training", "incorrect2_3")
    op.drop_column("training", "incorrect2_2")
    op.drop_column("training", "incorrect2_1")
    op.drop_column("training", "answer_2")
    op.drop_column("training", "question_2")
    # ### end Alembic commands ###
