"""empty message

Revision ID: 989d98a4c9f7
Revises: 7307d0b8860d
Create Date: 2023-03-22 13:45:53.917696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "989d98a4c9f7"
down_revision = "7307d0b8860d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training", sa.Column("difficulty", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("answer_question_1", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("false_1_question_1", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("false_2_question_1", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("false_3_question_1", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("answer_question_2", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("false_1_question_2", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("false_2_question_2", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("false_3_question_2", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("answer_question_3", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("false_1_question_3", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("false_2_question_3", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("false_3_question_3", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("answer_question_4", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("false_1_question_4", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("false_2_question_4", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("false_3_question_4", sa.String(), nullable=True)
    )
    op.drop_column("training", "answer_3")
    op.drop_column("training", "answer_5")
    op.drop_column("training", "answer_2")
    op.drop_column("training", "question_5")
    op.drop_column("training", "answer_4")
    op.drop_column("training", "answer_1")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training",
        sa.Column(
            "answer_1", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "answer_4", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "question_5", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "answer_2", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "answer_5", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "training",
        sa.Column(
            "answer_3", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("training", "false_3_question_4")
    op.drop_column("training", "false_2_question_4")
    op.drop_column("training", "false_1_question_4")
    op.drop_column("training", "answer_question_4")
    op.drop_column("training", "false_3_question_3")
    op.drop_column("training", "false_2_question_3")
    op.drop_column("training", "false_1_question_3")
    op.drop_column("training", "answer_question_3")
    op.drop_column("training", "false_3_question_2")
    op.drop_column("training", "false_2_question_2")
    op.drop_column("training", "false_1_question_2")
    op.drop_column("training", "answer_question_2")
    op.drop_column("training", "false_3_question_1")
    op.drop_column("training", "false_2_question_1")
    op.drop_column("training", "false_1_question_1")
    op.drop_column("training", "answer_question_1")
    op.drop_column("training", "difficulty")
    # ### end Alembic commands ###
