"""empty message

Revision ID: 9f7751b17601
Revises: 09098b77760b
Create Date: 2023-04-17 12:17:31.222622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9f7751b17601"
down_revision = "09098b77760b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("validation_rate", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "validation_rate")
    # ### end Alembic commands ###
