"""empty message

Revision ID: a05b002858b8
Revises: c6f372b1456e
Create Date: 2023-04-20 14:15:28.125582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05b002858b8'
down_revision = 'c6f372b1456e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('osm_username', sa.String(length=65), nullable=True))
    op.add_column('requests', sa.Column('osm_username', sa.String(length=65), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'osm_username')
    op.drop_column('payments', 'osm_username')
    # ### end Alembic commands ###
