"""empty message

Revision ID: a0b46e5dbdcd
Revises: 0cb003b31ceb
Create Date: 2023-05-08 13:54:06.150360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b46e5dbdcd'
down_revision = '0cb003b31ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_checklist_item', sa.Column('completion_date', sa.DateTime(), nullable=True))
    op.add_column('user_checklist_item', sa.Column('confirmation_date', sa.DateTime(), nullable=True))
    op.add_column('user_checklists', sa.Column('last_completion_date', sa.DateTime(), nullable=True))
    op.add_column('user_checklists', sa.Column('last_confirmation_date', sa.DateTime(), nullable=True))
    op.add_column('user_checklists', sa.Column('final_completion_date', sa.DateTime(), nullable=True))
    op.add_column('user_checklists', sa.Column('final_confirmation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_checklists', 'final_confirmation_date')
    op.drop_column('user_checklists', 'final_completion_date')
    op.drop_column('user_checklists', 'last_confirmation_date')
    op.drop_column('user_checklists', 'last_completion_date')
    op.drop_column('user_checklist_item', 'confirmation_date')
    op.drop_column('user_checklist_item', 'completion_date')
    # ### end Alembic commands ###
