"""empty message

Revision ID: a0cd0889b028
Revises: a0b46e5dbdcd
Create Date: 2023-05-08 14:03:35.958198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0cd0889b028'
down_revision = 'a0b46e5dbdcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_checklists', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_checklists', 'date_created')
    # ### end Alembic commands ###
