"""empty message

Revision ID: a335164828b2
Revises: 
Create Date: 2024-01-24 11:48:15.614184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a335164828b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_comment',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_comment_deleted_date'), 'checklist_comment', ['deleted_date'], unique=False)
    op.create_table('checklist_item',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('item_number', sa.Integer(), nullable=True),
    sa.Column('item_action', sa.String(), nullable=True),
    sa.Column('item_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_item_deleted_date'), 'checklist_item', ['deleted_date'], unique=False)
    op.create_table('checklists',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('total_payout', sa.Float(), nullable=True),
    sa.Column('validation_rate', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('visibility', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('active_status', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('completed', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('confirmed', sa.Boolean(), server_default='False', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklists_deleted_date'), 'checklists', ['deleted_date'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('payoneer_id', sa.String(length=65), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('user_name', sa.String(length=65), nullable=True),
    sa.Column('osm_username', sa.String(length=65), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payment_email', sa.String(length=65), nullable=True),
    sa.Column('task_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('date_paid', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('max_payment', sa.Float(), nullable=True),
    sa.Column('payment_due', sa.Float(), nullable=True),
    sa.Column('total_payout', sa.Float(), nullable=True),
    sa.Column('validation_rate_per_task', sa.Float(), nullable=True),
    sa.Column('mapping_rate_per_task', sa.Float(), nullable=True),
    sa.Column('max_editors', sa.Integer(), nullable=True),
    sa.Column('max_validators', sa.Integer(), nullable=True),
    sa.Column('total_editors', sa.BigInteger(), nullable=True),
    sa.Column('total_validators', sa.BigInteger(), nullable=True),
    sa.Column('total_tasks', sa.BigInteger(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('tasks_mapped', sa.BigInteger(), nullable=True),
    sa.Column('tasks_validated', sa.BigInteger(), nullable=True),
    sa.Column('tasks_invalidated', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('visibility', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('status', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('completed', sa.Boolean(), server_default='False', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_deleted_date'), 'projects', ['deleted_date'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('amount_requested', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=65), nullable=True),
    sa.Column('osm_username', sa.String(length=65), nullable=True),
    sa.Column('payment_email', sa.String(length=65), nullable=True),
    sa.Column('task_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('date_requested', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('validation_rate', sa.Float(), nullable=True),
    sa.Column('mapping_rate', sa.Float(), nullable=True),
    sa.Column('paid_out', sa.Boolean(), nullable=False),
    sa.Column('mapped', sa.Boolean(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('invalidated', sa.Boolean(), nullable=True),
    sa.Column('mapped_by', sa.String(length=80), nullable=False),
    sa.Column('validated_by', sa.String(length=80), nullable=False),
    sa.Column('unknown_validator', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_deleted_date'), 'tasks', ['deleted_date'], unique=False)
    op.create_table('training',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('training_type', sa.String(), nullable=True),
    sa.Column('point_value', sa.Integer(), nullable=True),
    sa.Column('training_url', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_deleted_date'), 'training', ['deleted_date'], unique=False)
    op.create_table('user_checklist_item',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('checklist_id', sa.BigInteger(), nullable=True),
    sa.Column('item_number', sa.Integer(), nullable=True),
    sa.Column('item_action', sa.String(), nullable=True),
    sa.Column('item_link', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('confirmation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_checklist_item_deleted_date'), 'user_checklist_item', ['deleted_date'], unique=False)
    op.create_table('user_checklists',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('checklist_id', sa.BigInteger(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('total_payout', sa.Float(), nullable=True),
    sa.Column('validation_rate', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('visibility', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('active_status', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('completed', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('confirmed', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('last_completion_date', sa.DateTime(), nullable=True),
    sa.Column('last_confirmation_date', sa.DateTime(), nullable=True),
    sa.Column('final_completion_date', sa.DateTime(), nullable=True),
    sa.Column('final_confirmation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_checklists_deleted_date'), 'user_checklists', ['deleted_date'], unique=False)
    op.create_table('users',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('payment_email', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('osm_username', sa.String(), nullable=True),
    sa.Column('org_id', sa.BigInteger(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('assigned_projects', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('assigned_checklists', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('mapper_level', sa.Integer(), nullable=True),
    sa.Column('mapper_points', sa.Integer(), nullable=True),
    sa.Column('validator_points', sa.Integer(), nullable=True),
    sa.Column('special_project_points', sa.Integer(), nullable=True),
    sa.Column('validation_payable_total', sa.Float(), server_default='0', nullable=True),
    sa.Column('mapping_payable_total', sa.Float(), server_default='0', nullable=True),
    sa.Column('checklist_payable_total', sa.Float(), server_default='0', nullable=True),
    sa.Column('payable_total', sa.Float(), server_default='0', nullable=True),
    sa.Column('requested_total', sa.Float(), server_default='0', nullable=True),
    sa.Column('paid_total', sa.Float(), server_default='0', nullable=True),
    sa.Column('total_tasks_mapped', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('total_tasks_validated', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('total_tasks_invalidated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_checklists_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('validator_total_checklists_confirmed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('validator_tasks_invalidated', sa.Integer(), server_default='0', nullable=True),
    sa.Column('validator_tasks_validated', sa.Integer(), server_default='0', nullable=True),
    sa.Column('requesting_payment', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('osm_username'),
    sa.UniqueConstraint('payment_email')
    )
    op.create_index(op.f('ix_users_deleted_date'), 'users', ['deleted_date'], unique=False)
    op.create_table('project_training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_completed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('training_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_question',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('training_id', sa.BigInteger(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_question_deleted_date'), 'training_question', ['deleted_date'], unique=False)
    op.create_table('user_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_question_answer',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('training_id', sa.BigInteger(), nullable=True),
    sa.Column('training_question_id', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.Boolean(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_question_id'], ['training_question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_question_answer_deleted_date'), 'training_question_answer', ['deleted_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_question_answer_deleted_date'), table_name='training_question_answer')
    op.drop_table('training_question_answer')
    op.drop_table('user_tasks')
    op.drop_index(op.f('ix_training_question_deleted_date'), table_name='training_question')
    op.drop_table('training_question')
    op.drop_table('training_completed')
    op.drop_table('project_users')
    op.drop_table('project_training')
    op.drop_index(op.f('ix_users_deleted_date'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_checklists_deleted_date'), table_name='user_checklists')
    op.drop_table('user_checklists')
    op.drop_index(op.f('ix_user_checklist_item_deleted_date'), table_name='user_checklist_item')
    op.drop_table('user_checklist_item')
    op.drop_index(op.f('ix_training_deleted_date'), table_name='training')
    op.drop_table('training')
    op.drop_index(op.f('ix_tasks_deleted_date'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('requests')
    op.drop_index(op.f('ix_projects_deleted_date'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('payments')
    op.drop_index(op.f('ix_checklists_deleted_date'), table_name='checklists')
    op.drop_table('checklists')
    op.drop_index(op.f('ix_checklist_item_deleted_date'), table_name='checklist_item')
    op.drop_table('checklist_item')
    op.drop_index(op.f('ix_checklist_comment_deleted_date'), table_name='checklist_comment')
    op.drop_table('checklist_comment')
    # ### end Alembic commands ###
