"""empty message

Revision ID: a41b16fb1581
Revises: ccf46bda94d9
Create Date: 2023-05-02 12:03:39.465471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41b16fb1581'
down_revision = 'ccf46bda94d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_comment',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_comment_deleted_date'), 'checklist_comment', ['deleted_date'], unique=False)
    op.drop_column('checklists', 'validator_comment')
    op.drop_column('checklists', 'user_comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklists', sa.Column('user_comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('checklists', sa.Column('validator_comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_checklist_comment_deleted_date'), table_name='checklist_comment')
    op.drop_table('checklist_comment')
    # ### end Alembic commands ###
