"""empty message

Revision ID: a5e27eba7cc8
Revises: 3df7dc6066e1
Create Date: 2023-03-07 09:43:02.310625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e27eba7cc8'
down_revision = '3df7dc6066e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'total_payout')
    op.drop_column('projects', 'rate_per_task')
    op.drop_column('projects', 'payment_due')
    op.drop_column('projects', 'max_payment')
    op.drop_column('tasks', 'rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('max_payment', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('payment_due', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('rate_per_task', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('total_payout', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
