"""empty message

Revision ID: a6b7f4eccb35
Revises: 577e0a60ee7a
Create Date: 2023-02-28 10:32:35.870664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a6b7f4eccb35"
down_revision = "577e0a60ee7a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payRequests",
        sa.Column("amount_requested", sa.Integer(), nullable=True),
    )
    op.alter_column(
        "payRequests",
        "id",
        existing_type=sa.BIGINT(),
        nullable=False,
        autoincrement=True,
        existing_server_default=sa.text(
            "nextval('\"payRequests_id_seq\"'::regclass)"
        ),
    )
    op.drop_column("payRequests", "amount")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payRequests",
        sa.Column("amount", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "payRequests",
        "id",
        existing_type=sa.BIGINT(),
        nullable=False,
        autoincrement=True,
        existing_server_default=sa.text(
            "nextval('\"payRequests_id_seq\"'::regclass)"
        ),
    )
    op.drop_column("payRequests", "amount_requested")
    # ### end Alembic commands ###
