"""empty message

Revision ID: ab8ccbb56b04
Revises: 5d5c09b5c53a
Create Date: 2023-03-01 17:13:22.612867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab8ccbb56b04"
down_revision = "5d5c09b5c53a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("amount_paid", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "amount_paid")
    # ### end Alembic commands ###
