"""empty message

Revision ID: b28ec3ab86da
Revises: 3bb688c855fe
Create Date: 2023-02-22 22:08:40.843725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b28ec3ab86da"
down_revision = "3bb688c855fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("tasks_mapped", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "projects",
        sa.Column("tasks_validated", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("tasks_invalidated", sa.BigInteger(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "tasks_invalidated")
    op.drop_column("projects", "tasks_validated")
    op.drop_column("projects", "tasks_mapped")
    # ### end Alembic commands ###
