"""empty message

Revision ID: b8d38a741f0f
Revises: a41b16fb1581
Create Date: 2023-05-02 16:30:09.766794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8d38a741f0f'
down_revision = 'a41b16fb1581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_checklist_item',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('item_number', sa.Integer(), nullable=True),
    sa.Column('item_action', sa.String(), nullable=True),
    sa.Column('item_link', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_checklist_item_deleted_date'), 'user_checklist_item', ['deleted_date'], unique=False)
    op.create_table('user_checklists',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('confirmed', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('payment_due', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_checklists_deleted_date'), 'user_checklists', ['deleted_date'], unique=False)
    op.drop_column('checklist_item', 'completed')
    op.drop_column('checklist_item', 'confirmed')
    op.drop_column('checklists', 'payment_due')
    op.drop_column('checklists', 'max_payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklists', sa.Column('max_payment', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('checklists', sa.Column('payment_due', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('checklist_item', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('checklist_item', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_checklists_deleted_date'), table_name='user_checklists')
    op.drop_table('user_checklists')
    op.drop_index(op.f('ix_user_checklist_item_deleted_date'), table_name='user_checklist_item')
    op.drop_table('user_checklist_item')
    # ### end Alembic commands ###
