"""empty message

Revision ID: b91babfb101c
Revises: 08f61e466739
Create Date: 2023-03-22 16:55:13.062298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b91babfb101c"
down_revision = "08f61e466739"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training",
        sa.Column("deleted_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("training_type", sa.String(), nullable=True),
        sa.Column("point_value", sa.Integer(), nullable=True),
        sa.Column("training_url", sa.String(), nullable=True),
        sa.Column("difficulty", sa.String(), nullable=True),
        sa.Column("question_1", sa.String(), nullable=True),
        sa.Column("answer_1", sa.String(), nullable=True),
        sa.Column("incorrect1_1", sa.String(), nullable=True),
        sa.Column("incorrect1_2", sa.String(), nullable=True),
        sa.Column("incorrect1_3", sa.String(), nullable=True),
        sa.Column("question_2", sa.String(), nullable=True),
        sa.Column("answer_2", sa.String(), nullable=True),
        sa.Column("incorrect2_1", sa.String(), nullable=True),
        sa.Column("incorrect2_2", sa.String(), nullable=True),
        sa.Column("incorrect2_3", sa.String(), nullable=True),
        sa.Column("question_3", sa.String(), nullable=True),
        sa.Column("answer_3", sa.String(), nullable=True),
        sa.Column("incorrect3_1", sa.String(), nullable=True),
        sa.Column("incorrect3_2", sa.String(), nullable=True),
        sa.Column("incorrect3_3", sa.String(), nullable=True),
        sa.Column("question_4", sa.String(), nullable=True),
        sa.Column("answer_4", sa.String(), nullable=True),
        sa.Column("incorrect4_1", sa.String(), nullable=True),
        sa.Column("incorrect4_2", sa.String(), nullable=True),
        sa.Column("incorrect4_3", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_deleted_date"),
        "training",
        ["deleted_date"],
        unique=False,
    )
    op.create_table(
        "training_completed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("training_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["training_id"], ["training.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("training_completed")
    op.drop_index(op.f("ix_training_deleted_date"), table_name="training")
    op.drop_table("training")
    # ### end Alembic commands ###
