"""empty message

Revision ID: bb56365d6a24
Revises: 6f1f8c3ab191
Create Date: 2023-02-28 10:41:48.726917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb56365d6a24'
down_revision = '6f1f8c3ab191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payRequests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payRequests',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('nextval(\'"payRequests_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('payoneer_id', sa.VARCHAR(length=65), autoincrement=False, nullable=True),
    sa.Column('amount_requested', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_requesting', sa.VARCHAR(length=65), autoincrement=False, nullable=True),
    sa.Column('payment_email', sa.VARCHAR(length=65), autoincrement=False, nullable=True),
    sa.Column('task_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('date_paid', sa.VARCHAR(length=65), autoincrement=False, nullable=True),
    sa.Column('date_requested', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payRequests_pkey')
    )
    # ### end Alembic commands ###
