"""empty message

Revision ID: c333dc50873e
Revises: 58c8320ff6c3
Create Date: 2023-03-22 13:50:44.218338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c333dc50873e"
down_revision = "58c8320ff6c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training", sa.Column("question_1", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("answer_1", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect1_1", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect1_2", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect1_3", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("question_2", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("answer_2", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect2_1", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect2_2", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect2_3", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("question_3", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("answer_3", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect3_1", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect3_2", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect3_3", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("question_4", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("answer_4", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect4_1", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect4_2", sa.String(), nullable=True)
    )
    op.add_column(
        "training", sa.Column("incorrect4_3", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("training", "incorrect4_3")
    op.drop_column("training", "incorrect4_2")
    op.drop_column("training", "incorrect4_1")
    op.drop_column("training", "answer_4")
    op.drop_column("training", "question_4")
    op.drop_column("training", "incorrect3_3")
    op.drop_column("training", "incorrect3_2")
    op.drop_column("training", "incorrect3_1")
    op.drop_column("training", "answer_3")
    op.drop_column("training", "question_3")
    op.drop_column("training", "incorrect2_3")
    op.drop_column("training", "incorrect2_2")
    op.drop_column("training", "incorrect2_1")
    op.drop_column("training", "answer_2")
    op.drop_column("training", "question_2")
    op.drop_column("training", "incorrect1_3")
    op.drop_column("training", "incorrect1_2")
    op.drop_column("training", "incorrect1_1")
    op.drop_column("training", "answer_1")
    op.drop_column("training", "question_1")
    # ### end Alembic commands ###
