"""empty message

Revision ID: c3c3a0684a81
Revises: 3080a80378b9
Create Date: 2023-03-23 13:46:22.239017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3c3a0684a81"
down_revision = "3080a80378b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training", sa.Column("incorrect", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("training", "incorrect")
    # ### end Alembic commands ###
