"""empty message

Revision ID: c466f07c7e5c
Revises: 62f26873ac9b
Create Date: 2023-03-22 15:15:47.289911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c466f07c7e5c"
down_revision = "62f26873ac9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "training", "id", existing_type=sa.INTEGER(), autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "training",
        "id",
        existing_type=sa.INTEGER(),
        nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
