"""empty message

Revision ID: c4734308ac8f
Revises: 5f907259b146
Create Date: 2023-07-25 10:06:06.828502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4734308ac8f'
down_revision = '5f907259b146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_question',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('training_id', sa.BigInteger(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_question_deleted_date'), 'training_question', ['deleted_date'], unique=False)
    op.create_table('training_question_answer',
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('training_id', sa.BigInteger(), nullable=True),
    sa.Column('training_question_id', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.Boolean(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_question_id'], ['training_question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_question_answer_deleted_date'), 'training_question_answer', ['deleted_date'], unique=False)
    op.drop_column('training', 'answer_3')
    op.drop_column('training', 'incorrect1_3')
    op.drop_column('training', 'incorrect2_2')
    op.drop_column('training', 'incorrect4_2')
    op.drop_column('training', 'question_3')
    op.drop_column('training', 'answer_4')
    op.drop_column('training', 'question_2')
    op.drop_column('training', 'incorrect3_1')
    op.drop_column('training', 'incorrect2_3')
    op.drop_column('training', 'answer_1')
    op.drop_column('training', 'question_4')
    op.drop_column('training', 'answer_2')
    op.drop_column('training', 'incorrect3_3')
    op.drop_column('training', 'incorrect1_1')
    op.drop_column('training', 'incorrect4_3')
    op.drop_column('training', 'incorrect2_1')
    op.drop_column('training', 'incorrect3_2')
    op.drop_column('training', 'incorrect4_1')
    op.drop_column('training', 'question_1')
    op.drop_column('training', 'incorrect1_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('incorrect1_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('question_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('incorrect4_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('incorrect3_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('incorrect2_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('incorrect4_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('incorrect1_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('incorrect3_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('answer_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('question_4', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('answer_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('incorrect2_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('incorrect3_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('question_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('answer_4', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('question_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('incorrect4_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('incorrect2_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('incorrect1_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('training', sa.Column('answer_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_training_question_answer_deleted_date'), table_name='training_question_answer')
    op.drop_table('training_question_answer')
    op.drop_index(op.f('ix_training_question_deleted_date'), table_name='training_question')
    op.drop_table('training_question')
    # ### end Alembic commands ###
