"""empty message

Revision ID: c6f372b1456e
Revises: f5f731ab7218
Create Date: 2023-04-19 10:22:57.279998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6f372b1456e'
down_revision = 'f5f731ab7218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'max_editors',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('tasks', sa.Column('mapping_rate', sa.Float(), nullable=True))
    op.drop_column('tasks', 'rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'mapping_rate')
    op.alter_column('projects', 'max_editors',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
