"""empty message

Revision ID: c869ebb40b0e
Revises: b28ec3ab86da
Create Date: 2023-02-24 13:20:35.847976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c869ebb40b0e"
down_revision = "b28ec3ab86da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_users")
    # ### end Alembic commands ###
