"""empty message

Revision ID: ccf46bda94d9
Revises: fd67ddb3ffe2
Create Date: 2023-05-02 11:52:57.665027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf46bda94d9'
down_revision = 'fd67ddb3ffe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklists', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklists', sa.Column('status', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
