"""empty message

Revision ID: d018e4ae2137
Revises: a6b7f4eccb35
Create Date: 2023-02-28 10:39:28.499840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd018e4ae2137'
down_revision = 'a6b7f4eccb35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_users')
    op.drop_table('payRequests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payRequests',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('nextval(\'"payRequests_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('payoneer_id', sa.VARCHAR(length=65), autoincrement=False, nullable=True),
    sa.Column('user_requesting', sa.VARCHAR(length=65), autoincrement=False, nullable=True),
    sa.Column('payment_email', sa.VARCHAR(length=65), autoincrement=False, nullable=True),
    sa.Column('task_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('date_paid', sa.VARCHAR(length=65), autoincrement=False, nullable=True),
    sa.Column('date_requested', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('amount_requested', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payRequests_pkey')
    )
    op.create_table('project_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_users_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='project_users_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='project_users_pkey')
    )
    # ### end Alembic commands ###
