"""empty message

Revision ID: d12095b6dada
Revises: 85262c64e8d6
Create Date: 2023-02-22 15:32:22.529232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d12095b6dada"
down_revision = "85262c64e8d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "visibility", sa.Boolean(), server_default="False", nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "visibility")
    # ### end Alembic commands ###
