"""empty message

Revision ID: d1868ed81960
Revises: 84a821ffc482
Create Date: 2023-03-01 14:14:35.963522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1868ed81960'
down_revision = '84a821ffc482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'date_paid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('date_paid', sa.VARCHAR(length=65), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
