"""empty message

Revision ID: d2f630510f21
Revises: 46ef198f16bc
Create Date: 2023-02-28 22:09:04.052279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d2f630510f21"
down_revision = "46ef198f16bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "amount_paid")
    op.drop_column("requests", "amount_requested")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests",
        sa.Column(
            "amount_requested",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "payments",
        sa.Column(
            "amount_paid", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
