"""empty message

Revision ID: e19005a5a156
Revises: 80f35b1129df
Create Date: 2023-02-20 18:00:02.805571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19005a5a156'
down_revision = '80f35b1129df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_city_key', 'users', type_='unique')
    op.drop_constraint('users_country_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_country_key', 'users', ['country'])
    op.create_unique_constraint('users_city_key', 'users', ['city'])
    # ### end Alembic commands ###
