"""empty message

Revision ID: ea39a0d14d10
Revises: 64f00bafec75
Create Date: 2023-02-28 10:23:23.002764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea39a0d14d10'
down_revision = '64f00bafec75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('mapped', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('invalidated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'invalidated')
    op.drop_column('tasks', 'mapped')
    # ### end Alembic commands ###
