"""empty message

Revision ID: eadc6f28b106
Revises: 19c3d19399c2
Create Date: 2023-02-28 11:24:06.905145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eadc6f28b106'
down_revision = '19c3d19399c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('org_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'org_id')
    # ### end Alembic commands ###
