"""empty message

Revision ID: f5f1770a0697
Revises: a5e27eba7cc8
Create Date: 2023-03-07 09:47:16.767470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f1770a0697'
down_revision = 'a5e27eba7cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('max_payment', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('payment_due', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('total_payout', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('rate_per_task', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'rate')
    op.drop_column('projects', 'rate_per_task')
    op.drop_column('projects', 'total_payout')
    op.drop_column('projects', 'payment_due')
    op.drop_column('projects', 'max_payment')
    # ### end Alembic commands ###
