"""empty message

Revision ID: f5f731ab7218
Revises: 0d84ccb7b071
Create Date: 2023-04-17 14:47:18.890995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f5f731ab7218"
down_revision = "0d84ccb7b071"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("validation_rate_per_task", sa.Float(), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("mapping_rate_per_task", sa.Float(), nullable=True),
    )
    op.add_column(
        "projects", sa.Column("max_validators", sa.Integer(), nullable=True)
    )
    op.add_column(
        "projects",
        sa.Column("total_validators", sa.BigInteger(), nullable=True),
    )
    op.drop_column("projects", "rate_per_task")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "rate_per_task",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("projects", "total_validators")
    op.drop_column("projects", "max_validators")
    op.drop_column("projects", "mapping_rate_per_task")
    op.drop_column("projects", "validation_rate_per_task")
    # ### end Alembic commands ###
