"""empty message

Revision ID: f6ee93084670
Revises: 49349df8f7f2
Create Date: 2023-04-17 12:14:55.066592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ee93084670'
down_revision = '49349df8f7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('validator_tasks_invalidated', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('validator_tasks_validated', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'validator_tasks_validated')
    op.drop_column('users', 'validator_tasks_invalidated')
    # ### end Alembic commands ###
